--Câu 2: MAX
DECLARE @MAXLUONG FLOAT
SELECT @MAXLUONG=MAX(LUONG)
FROM NHANVIEN

-- Câu 2: AVG
DECLARE @AVGLUONG FLOAT
SELECT  @AVGLUONG=AVG(LUONG)
FROM NHANVIEN
SELECT HONV,TENLOT,TENNV
FROM NHANVIEN
WHERE (LUONG>@AVGLUONG) AND (PHG = 5)

-- Câu 3:
DECLARE @AVGLUONG FLOAT
SELECT  @AVGLUONG=AVG(LUONG)
FROM NHANVIEN
SELECT TENPHG,COUNT (*) AS SOLUONG
FROM PHONGBAN,NHANVIEN
WHERE  MAPHG =PHG 
GROUP BY TENPHG
HAVING @AVGLUONG>30000

--Câu 4:
SELECT TENPHG,COUNT (*) AS SOLUONG
FROM PHONGBAN,DEAN
WHERE  MAPHG =PHONG
GROUP BY TENPHG